"""Storage abstraction for openPasture.

All tool handlers should talk to this protocol rather than a concrete backend.
"""

from __future__ import annotations

from typing import Protocol

from openpasture.domain import DailyBrief, Farm, Herd, KnowledgeEntry, MovementDecision, Observation, Paddock


class FarmStore(Protocol):
    """Protocol implemented by all persistence backends."""

    def get_farm(self, farm_id: str) -> Farm | None: ...
    def create_farm(self, farm: Farm) -> str: ...
    def update_farm(self, farm_id: str, **updates: object) -> None: ...

    def get_paddock(self, paddock_id: str) -> Paddock | None: ...
    def list_paddocks(self, farm_id: str) -> list[Paddock]: ...
    def create_paddock(self, paddock: Paddock) -> str: ...

    def create_herd(self, herd: Herd) -> str: ...
    def get_herds(self, farm_id: str) -> list[Herd]: ...
    def update_herd_position(self, herd_id: str, paddock_id: str) -> None: ...

    def record_observation(self, observation: Observation) -> str: ...
    def get_recent_observations(self, farm_id: str, days: int = 7) -> list[Observation]: ...
    def get_paddock_observations(self, paddock_id: str, days: int = 7) -> list[Observation]: ...

    def create_plan(self, plan: MovementDecision) -> str: ...
    def get_plan(self, plan_id: str) -> MovementDecision | None: ...
    def get_latest_plan(self, farm_id: str) -> MovementDecision | None: ...
    def update_plan_status(self, plan_id: str, status: str, feedback: str | None = None) -> None: ...

    def store_knowledge(self, entries: list[KnowledgeEntry]) -> list[str]: ...
    def search_knowledge(self, query: str, farm_id: str | None = None, limit: int = 5) -> list[KnowledgeEntry]: ...

    def save_daily_brief(self, brief: DailyBrief) -> str: ...
