"""Storage abstraction for openPasture.

All tool handlers should talk to this protocol rather than a concrete backend.
"""

from __future__ import annotations

from typing import Protocol

from openpasture.domain import (
    DailyBrief,
    DataPipeline,
    Farm,
    FarmerAction,
    Herd,
    LandUnit,
    MovementDecision,
    Observation,
)


class FarmStore(Protocol):
    """Protocol implemented by all persistence backends."""

    def list_farms(self) -> list[Farm]: ...
    def get_farm(self, farm_id: str) -> Farm | None: ...
    def create_farm(self, farm: Farm) -> str: ...
    def update_farm(self, farm_id: str, **updates: object) -> None: ...

    def get_land_unit(self, land_unit_id: str) -> LandUnit | None: ...
    def list_land_units(self, farm_id: str, unit_type: str | None = None) -> list[LandUnit]: ...
    def upsert_land_unit(self, land_unit: LandUnit) -> str: ...
    def update_land_unit(self, land_unit_id: str, **updates: object) -> None: ...

    def create_herd(self, herd: Herd) -> str: ...
    def get_herds(self, farm_id: str) -> list[Herd]: ...
    def update_herd_position(self, herd_id: str, paddock_id: str) -> None: ...

    def record_observation(self, observation: Observation) -> str: ...
    def get_recent_observations(self, farm_id: str, days: int = 7) -> list[Observation]: ...
    def get_paddock_observations(self, paddock_id: str, days: int = 7) -> list[Observation]: ...

    def create_pipeline(self, pipeline: DataPipeline) -> str: ...
    def get_pipeline(self, pipeline_id: str) -> DataPipeline | None: ...
    def list_pipelines(self, farm_id: str) -> list[DataPipeline]: ...
    def update_pipeline(self, pipeline_id: str, **updates: object) -> None: ...

    def create_farmer_action(self, action: FarmerAction) -> str: ...
    def list_pending_actions(self, farm_id: str) -> list[FarmerAction]: ...
    def resolve_farmer_action(self, action_id: str, resolution: str) -> None: ...

    def create_plan(self, plan: MovementDecision) -> str: ...
    def get_plan(self, plan_id: str) -> MovementDecision | None: ...
    def get_latest_plan(self, farm_id: str) -> MovementDecision | None: ...
    def update_plan_status(self, plan_id: str, status: str, feedback: str | None = None) -> None: ...

    def save_daily_brief(self, brief: DailyBrief) -> str: ...
