"""Storage abstraction for openPasture.

All tool handlers should talk to this protocol rather than a concrete backend.
"""

from __future__ import annotations

from typing import Protocol

from openpasture.domain import DailyBrief, Farm, Herd, KnowledgeEntry, MovementDecision, Observation, Paddock


class FarmStore(Protocol):
    """Protocol implemented by all persistence backends."""

    def get_farm(self, farm_id: str) -> Farm | None: ...
    def create_farm(self, farm: Farm) -> str: ...
    def list_paddocks(self, farm_id: str) -> list[Paddock]: ...
    def create_paddock(self, paddock: Paddock) -> str: ...
    def list_herds(self, farm_id: str) -> list[Herd]: ...
    def record_observation(self, observation: Observation) -> str: ...
    def get_recent_observations(self, farm_id: str, days: int = 7) -> list[Observation]: ...
    def create_movement_decision(self, decision: MovementDecision) -> str: ...
    def get_latest_movement_decision(self, farm_id: str) -> MovementDecision | None: ...
    def store_knowledge_entries(self, entries: list[KnowledgeEntry]) -> list[str]: ...
    def search_knowledge(self, query: str, farm_id: str | None = None, limit: int = 5) -> list[KnowledgeEntry]: ...
    def save_daily_brief(self, brief: DailyBrief) -> str: ...
